# Generated by Django 5.2.7 on 2025-10-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='type',
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.ManyToManyField(to='courses.coursetype'),
        ),
    ]
