# Generated by Django 5.2.7 on 2025-10-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursetype_remove_course_type_course_type'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoursOffering',
            new_name='CourseOffering',
        ),
    ]
