# Generated by Django 5.2.7 on 2025-10-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_coursoffering_courseoffering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseoffering',
            options={'ordering': ['course', 'period']},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['year', 'term']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
