# Generated by Django 5.2.7 on 2025-10-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courseoffering_options_alter_semester_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('program', 'level')},
        ),
    ]
