# Generated by Django 5.2.7 on 2025-10-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['program', 'level']},
        ),
    ]
