# Generated by Django 5.2.7 on 2025-11-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='level_sub',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='level_suffix',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='graduate',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='undergrad',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='term',
            field=models.CharField(choices=[('0WI', 'Winter'), ('2SP', 'Spring'), ('4SU', 'Summer'), ('8AU', 'Autumn')], max_length=5),
        ),
    ]
