# Generated by Django 5.2.7 on 2025-11-07 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_courseoffering_level_sub_courseoffering_level_suffix_and_more'),
        ('faculty', '0005_person_other_names_alter_person_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, null=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseoffering')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.person')),
            ],
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='lecturers',
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='lecturers',
            field=models.ManyToManyField(through='courses.Instructor', to='faculty.person'),
        ),
    ]
