# Generated by Django 5.2.7 on 2025-10-29 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AWP', 'AWP'), ('GRT', 'GRT')], max_length=10)),
                ('tid', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('federal', models.BooleanField()),
                ('report_date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('spn_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Investigator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PI', 'PI'), ('CO-PI', 'CO PI')], max_length=10)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grants.grant')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.person')),
            ],
        ),
        migrations.AddField(
            model_name='grant',
            name='investigators',
            field=models.ManyToManyField(through='grants.Investigator', to='faculty.person'),
        ),
        migrations.AddField(
            model_name='grant',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.sponsor'),
        ),
    ]
