# Generated by Django 5.2.7 on 2025-10-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='status',
            field=models.CharField(choices=[('not_funded', 'Not Funded'), ('received', 'Award Received'), ('pending', 'Submitted to Sponsor/Pending'), ('no_data', 'No Award Data')], max_length=20),
        ),
    ]
