# Generated by Django 5.2.7 on 2025-11-10 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_person_other_names_alter_person_first_name_and_more'),
        ('grants', '0002_alter_grant_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigator',
            name='grant',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='federal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='level',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsor',
            name='type',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wd_id', models.CharField(max_length=50)),
                ('ps_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('not_funded', 'Not Funded'), ('received', 'Award Received'), ('pending', 'Submitted to Sponsor/Pending'), ('no_data', 'No Award Data')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('report_date', models.DateField()),
                ('direct_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fa_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investigators', models.ManyToManyField(through='grants.Investigator', to='faculty.person')),
                ('prime_sponsor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prime_proposals', to='grants.sponsor')),
                ('sponsor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.sponsor')),
            ],
        ),
        migrations.AddField(
            model_name='investigator',
            name='proposal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='grants.proposal'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Grant',
        ),
    ]
