# Generated by Django 5.2.7 on 2025-11-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0003_remove_investigator_grant_sponsor_federal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='ps_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='wd_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='spn_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
