# Generated by Django 5.2.7 on 2025-11-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0004_alter_proposal_ps_id_alter_proposal_wd_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='report_date',
            field=models.DateField(null=True),
        ),
    ]
