# Generated by Django 5.2.7 on 2025-11-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0005_alter_proposal_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='fiscal_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
