# Generated by Django 5.2.7 on 2025-11-14 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_person_other_names_alter_person_first_name_and_more'),
        ('grants', '0006_proposal_fiscal_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wd_id', models.CharField(max_length=50, null=True)),
                ('ps_id', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('beginning_fiscal_year', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('prime_sponsor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prime_awards', to='grants.sponsor')),
                ('proposal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.proposal')),
                ('sponsor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='Collaborators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PI', 'PI'), ('CO-PI', 'CO PI')], max_length=10)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grants.award')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.person')),
            ],
        ),
        migrations.AddField(
            model_name='award',
            name='investigators',
            field=models.ManyToManyField(through='grants.Collaborators', to='faculty.person'),
        ),
    ]
