# Generated by Django 5.2.7 on 2025-11-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0007_award_collaborators_award_investigators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
