# Generated by Django 5.2.7 on 2025-11-14 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_person_other_names_alter_person_first_name_and_more'),
        ('grants', '0008_alter_award_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collaborators',
            new_name='Collaborator',
        ),
    ]
