# Generated by Django 5.2.7 on 2025-11-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0009_rename_collaborators_collaborator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='ps_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='wd_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='award',
            unique_together={('wd_id', 'ps_id')},
        ),
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together={('wd_id', 'ps_id')},
        ),
    ]
