# Generated by Django 5.2.7 on 2025-10-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='employee_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
