# Generated by Django 5.2.7 on 2025-10-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_remove_person_name_person_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='employee_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
