# Generated by Django 5.2.7 on 2025-11-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_alter_person_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='other_names',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
