# Generated by Django 5.2.7 on 2025-11-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_person_other_names_alter_person_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='employee_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
