# Generated by Django 5.2.7 on 2025-11-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_alter_person_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='college',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
